version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "chmod -R 777 storage && apache2-foreground"
    ports:
      - "21465:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis
    networks:
      - my-network
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - my-network

volumes:
  redis-data:
    driver: local

networks:
    my-network:
        driver: bridge